[package]
name = "roar"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "^0.8.3"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.11"
rattler = { git = "https://github.com/baszalmstra/rattler" }
anyhow = "1.0.63"
walkdir = "2.3.2"
sha2 = "0.10.5"
hex = "0.4.3"
serde_json = "1.0.85"
tera = "1.17.0"
starlark = { git = "https://github.com/facebookexperimental/starlark-rust"}
tempdir = "0.3.7"
flate2 = "1.0.24"
tar = "0.4.38"
bzip2 = "0.4.3"
reqwest = "0.11.11"
futures = "0.3.24"
tokio = "1.21.0"
